version: 2
jobs:
  build:
    docker:
      - image: drevops/ci-builder
    working_directory: /app
    steps:
      - checkout
      - run:
          name: Check spelling
          command: ./scripts/check-spell.sh
      - run:
          name: Install ruby and bundler
          command: |
            apt-get update
            apt-get install -y ruby-full zlib1g-dev
            gem install bundler
      - run:
          name: Build site
          command: |
            cd docs
            bundle install
            bundle exec jekyll build
      - store_artifacts:
          path: docs/_site
